import { InformationProduct } from "../../components/InformationProduct";
import { Layout } from "../../components/Layout";
import Head from "next/head";


export default function Index() {
  return (
    <>
      <Head>
        <title>Traki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InformationProduct
        
         img="/img/trakiwoman/traki1.jpg"
        name="Talego Dulce"
        precio={100000}
        description="Talego corto unicolor, en popelina, manga tira con gola, encauchado atrás"
        id="DU02CV"
        tallas={["XS","S","M","L","XL"]}
        color={["Negro", "Azul", "Blanco","Rojo"]}
        cantidad={10}
        buttoncart="Añadir al carrito"
        buttonshopping="Comprar Ahora"

        />
      </Layout>

    </>

  )
}
