
import { Container } from '@/components/Container'
import { Layout } from '@/components/Layout'
import { ListProductViews } from '@/components/ListProductViews'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title> Caballeros </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Container>
                    <ListProductViews
                        productViews={[
                            {
                                img: "/img/trakiman/TrakiMan1.jpg",
                                name: " Camisa",
                                description: "Casual ",
                                precio: 90000,
                                id: "h1"
                            },
                            {
                                img: "/img/trakiman/TrakiMan2.jpg",
                                name: "Chaleco",
                                description: " Tela unicolor",
                                precio: 300000,
                                id: "h2"
                            },
                            {
                                img: "/img/trakiman/TrakiMan3.jpg",
                                name: "Combinacion",
                                description: "Basicos",
                                precio: 100000,
                                id: "h3"
                            },
                            {
                                img: "/img/trakiman/TrakiMan4.jpg",
                                name: "Conjunto Oscar",
                                description: "Tela suave,fresca,estampado,",
                                precio: 120000,
                                id: "h4"
                            },
                            {
                                img: "/img/trakiman/TrakiMan5.jpg",
                                name: "Pantalon",
                                description: "Versatil,tela fresca",
                                precio: 13000,
                                id: "h5"
                            },
                            {
                                img: "/img/trakiman/TrakiMan6.jpg",
                                name: "Chaleco ",
                                description: "Ideal para el frio",
                                precio: 50000,
                                id: "h6"
                            },
                            {
                                img: "/img/trakiman/TrakiMan7.jpg",
                                name: "Combinacion Foil BARBIE",
                                description: "En tendencia",
                                precio: 80000,
                                id: "h7"
                            },
                            {
                                img: "/img/trakiman/TrakiMan8.jpg",
                                name: "Conjunto Foil BARBIE",
                                description: " En tendencia",
                                precio: 80000,
                                id: "h8"
                            },
                            {
                                img: "/img/trakiman/TrakiMan9.jpg",
                                name: "Camisa Easy Care",
                                description: "Camisa con cuello solapas y manga larga",
                                precio: 20000,
                                id: "h9"
                            },
                            {
                                img: "/img/trakiman/TrakiMan10.jpg",
                                name: "Camisa Patchwork Crochet",
                                description: "Camisa confeccionada con crochet ",
                                precio: 180000,
                                id: "h10"
                            },
                            {
                                img: "/img/trakiman/TrakiMan11.jpg",
                                name: "Camisa Bolsillo Utility",
                                description: " Camisa relaxed fit confeccionada en tejido de algodón",
                                precio: 150000,
                                id: "h11"
                            },
                            {
                                img: "/img/trakiman/TrakiMan12.jpg",
                                name: "Camisa Algodon",
                                description: "Tela fresca,unicolor",
                                precio: 250000,
                                id: "h12"
                            },
                            {
                                img: "/img/trakiman/TrakiMan13.jpg",
                                name: "Conjunto Estampados Bandas",
                                description: "Outfit casual",
                                precio: 25000,
                                id: "h13"
                            },
                            {
                                img: "/img/trakiman/TrakiMan14.jpg",
                                name: "Estructura Easy Care",
                                description: "Unicolor,versatil",
                                precio: 20000,
                                id: "h14"
                            },
                            {
                                img: "/img/trakiman/TrakiMan15.jpg",
                                name: "Camisa Bordado",
                                description: "Camisa relaxed fit, ajustable ",
                                precio: 90000,
                                id: "h15"
                            },
                            {
                                img: "/img/trakiman/TrakiMan1.jpg",
                                name: " Camisa",
                                description: "Casual ",
                                precio: 90000,
                                id: "h1"
                            },
                            {
                                img: "/img/trakiman/TrakiMan2.jpg",
                                name: "Chaleco",
                                description: " Tela unicolor",
                                precio: 300000,
                                id: "h2"
                            },
                            {
                                img: "/img/trakiman/TrakiMan3.jpg",
                                name: "Combinacion",
                                description: "Basicos",
                                precio: 100000,
                                id: "h3"
                            },
                            {
                                img: "/img/trakiman/TrakiMan4.jpg",
                                name: "Conjunto Oscar",
                                description: "Tela suave,fresca,estampado,",
                                precio: 120000,
                                id: "h4"
                            },
                            {
                                img: "/img/trakiman/TrakiMan5.jpg",
                                name: "Pantalon",
                                description: "Versatil,tela fresca",
                                precio: 13000,
                                id: "h5"
                            },
                            {
                                img: "/img/trakiman/TrakiMan6.jpg",
                                name: "Chaleco ",
                                description: "Ideal para el frio",
                                precio: 50000,
                                id: "h6"
                            },
                            {
                                img: "/img/trakiman/TrakiMan7.jpg",
                                name: "Combinacion Foil BARBIE",
                                description: "En tendencia",
                                precio: 80000,
                                id: "h7"
                            },
                            {
                                img: "/img/trakiman/TrakiMan8.jpg",
                                name: "Conjunto Foil BARBIE",
                                description: " En tendencia",
                                precio: 80000,
                                id: "h8"
                            },
                            {
                                img: "/img/trakiman/TrakiMan9.jpg",
                                name: "Camisa Easy Care",
                                description: "Camisa con cuello solapas y manga larga",
                                precio: 20000,
                                id: "h9"
                            },
                            {
                                img: "/img/trakiman/TrakiMan10.jpg",
                                name: "Camisa Patchwork Crochet",
                                description: "Camisa confeccionada con crochet ",
                                precio: 180000,
                                id: "h10"
                            },
                            {
                                img: "/img/trakiman/TrakiMan11.jpg",
                                name: "Camisa Bolsillo Utility",
                                description: " Camisa relaxed fit confeccionada en tejido de algodón",
                                precio: 150000,
                                id: "h11"
                            },
                            {
                                img: "/img/trakiman/TrakiMan12.jpg",
                                name: "Camisa Algodon",
                                description: "Tela fresca,unicolor",
                                precio: 250000,
                                id: "h12"
                            },
                            {
                                img: "/img/trakiman/TrakiMan13.jpg",
                                name: "Conjunto Estampados Bandas",
                                description: "Outfit casual",
                                precio: 25000,
                                id: "h13"
                            },
                            {
                                img: "/img/trakiman/TrakiMan14.jpg",
                                name: "Estructura Easy Care",
                                description: "Unicolor,versatil",
                                precio: 20000,
                                id: "h14"
                            },
                            {
                                img: "/img/trakiman/TrakiMan15.jpg",
                                name: "Camisa Bordado",
                                description: "Camisa relaxed fit, ajustable ",
                                precio: 90000,
                                id: "h15"
                            },
                            {
                                img: "/img/trakiman/TrakiMan1.jpg",
                                name: " Camisa",
                                description: "Casual ",
                                precio: 90000,
                                id: "h1"
                            },
                            {
                                img: "/img/trakiman/TrakiMan2.jpg",
                                name: "Chaleco",
                                description: " Tela unicolor",
                                precio: 300000,
                                id: "h2"
                            },
                            {
                                img: "/img/trakiman/TrakiMan3.jpg",
                                name: "Combinacion",
                                description: "Basicos",
                                precio: 100000,
                                id: "h3"
                            },
                            {
                                img: "/img/trakiman/TrakiMan4.jpg",
                                name: "Conjunto Oscar",
                                description: "Tela suave,fresca,estampado,",
                                precio: 120000,
                                id: "h4"
                            },
                            {
                                img: "/img/trakiman/TrakiMan5.jpg",
                                name: "Pantalon",
                                description: "Versatil,tela fresca",
                                precio: 13000,
                                id: "h5"
                            },
                            {
                                img: "/img/trakiman/TrakiMan6.jpg",
                                name: "Chaleco ",
                                description: "Ideal para el frio",
                                precio: 50000,
                                id: "h6"
                            },
                            {
                                img: "/img/trakiman/TrakiMan7.jpg",
                                name: "Combinacion Foil BARBIE",
                                description: "En tendencia",
                                precio: 80000,
                                id: "h7"
                            },
                            {
                                img: "/img/trakiman/TrakiMan8.jpg",
                                name: "Conjunto Foil BARBIE",
                                description: " En tendencia",
                                precio: 80000,
                                id: "h8"
                            },
                            {
                                img: "/img/trakiman/TrakiMan9.jpg",
                                name: "Camisa Easy Care",
                                description: "Camisa con cuello solapas y manga larga",
                                precio: 20000,
                                id: "h9"
                            },
                            {
                                img: "/img/trakiman/TrakiMan10.jpg",
                                name: "Camisa Patchwork Crochet",
                                description: "Camisa confeccionada con crochet ",
                                precio: 180000,
                                id: "h10"
                            },
                            {
                                img: "/img/trakiman/TrakiMan11.jpg",
                                name: "Camisa Bolsillo Utility",
                                description: " Camisa relaxed fit confeccionada en tejido de algodón",
                                precio: 150000,
                                id: "h11"
                            },
                            {
                                img: "/img/trakiman/TrakiMan12.jpg",
                                name: "Camisa Algodon",
                                description: "Tela fresca,unicolor",
                                precio: 250000,
                                id: "h12"
                            },
                            {
                                img: "/img/trakiman/TrakiMan13.jpg",
                                name: "Conjunto Estampados Bandas",
                                description: "Outfit casual",
                                precio: 25000,
                                id: "h13"
                            },
                            {
                                img: "/img/trakiman/TrakiMan14.jpg",
                                name: "Estructura Easy Care",
                                description: "Unicolor,versatil",
                                precio: 20000,
                                id: "h14"
                            },
                            {
                                img: "/img/trakiman/TrakiMan15.jpg",
                                name: "Camisa Bordado",
                                description: "Camisa relaxed fit, ajustable ",
                                precio: 90000,
                                id: "h15"
                            },
                           
                           
                           
                           

                        ]}

                    />
                </Container>

            </Layout>

        </>
    )
}
