
import { Container } from '@/components/Container'
import { Layout } from '@/components/Layout'
import { ListProductViews } from '@/components/ListProductViews'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Hogar</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Container>
                    <ListProductViews
                        productViews={[


                            {
                                img: "/img/trakihome/trakihome7.jpg",
                                name: "Mueble para TV hasta 50” Andorra Bellota",
                                description: "Mueble para tv con, espacio para almacenar ",
                                precio: 180000,
                                id: "c1"
                            },
                            {
                                img: "/img/trakihome/trakihome8.jpg",
                                name: "Mesa de noche Hanaki",
                                description: "Mesa de noche Hanaki",
                                precio: 25000,
                                id: "c2"
                            },
                            {
                                img: "/img/trakihome/trakihome9.jpg",
                                name: " Comedor Marsella ",
                                description: "Mesa de Comedor Marsella 4 Puestos",
                                precio: 100000,
                                id: "c3"
                            },
                            {
                                img: "/img/trakihome/trakihome10.jpg",
                                name: "Gabinete de baño",
                                description: "Tiene espejo. Es de muy fácil armado,",
                                precio: 100000,
                                id: "c4"
                            },
                            {
                                img: "/img/trakihome/trakihome11.jpg",
                                name: "Silla Barra Dais negra ",
                                description: "Cuero Sintético",
                                precio: 25000,
                                id: "c5"
                            },
                            {
                                img: "/img/trakihome/trakihome12.jpg",
                                name: "Auxiliar de cocina",
                                description: "Auxiliar de cocina Cala Wengue Ibiza",
                                precio: 13000,
                                id: "c6"
                            },
                            {
                                img: "/img/trakihome/trakihome13.jpg",
                                name: "Vinilo Decorativo ",
                                description: "Vinilo Decorativo de Pájaros al Atardecer",
                                precio: 180000,
                                id: "c7"
                            },
                            {
                                img: "/img/trakihome/trakihome14.jpg",
                                name: "Cuadro Abstracto  ",
                                description: "Cuadro Abstracto Cielo con Nubes",
                                precio: 110000,
                                id: "c8"
                            },
                            {
                                img: "/img/trakihome/trakihome15.jpg",
                                name: "Archivador Aéreo",
                                description: "Archivador aéreo en madera modular",
                                precio: 130000,
                                id: "c9"
                            },
                            {
                                img: "/img/trakihome/trakihome16.jpg",
                                name: "Base Cama ",
                                description: "La Base Cama Versalles Doble de diseño moderno y elegante",
                                precio: 20000,
                                id: "c10"
                            },

                            {
                                img: "/img/trakihome/trakihome7.jpg",
                                name: "Mueble para TV hasta 50” Andorra Bellota",
                                description: "Mueble para tv con, espacio para almacenar ",
                                precio: 180000,
                                id: "c1"
                            },
                            {
                                img: "/img/trakihome/trakihome8.jpg",
                                name: "Mesa de noche Hanaki",
                                description: "Mesa de noche Hanaki",
                                precio: 25000,
                                id: "c2"
                            },
                            {
                                img: "/img/trakihome/trakihome9.jpg",
                                name: " Comedor Marsella ",
                                description: "Mesa de Comedor Marsella 4 Puestos",
                                precio: 100000,
                                id: "c3"
                            },
                            {
                                img: "/img/trakihome/trakihome10.jpg",
                                name: "Gabinete de baño",
                                description: "Tiene espejo. Es de muy fácil armado,",
                                precio: 100000,
                                id: "c4"
                            },
                            {
                                img: "/img/trakihome/trakihome11.jpg",
                                name: "Silla Barra Dais negra ",
                                description: "Cuero Sintético",
                                precio: 25000,
                                id: "c5"
                            },
                            {
                                img: "/img/trakihome/trakihome12.jpg",
                                name: "Auxiliar de cocina",
                                description: "Auxiliar de cocina Cala Wengue Ibiza",
                                precio: 13000,
                                id: "c6"
                            },
                            {
                                img: "/img/trakihome/trakihome13.jpg",
                                name: "Vinilo Decorativo ",
                                description: "Vinilo Decorativo de Pájaros al Atardecer",
                                precio: 180000,
                                id: "c7"
                            },
                            {
                                img: "/img/trakihome/trakihome14.jpg",
                                name: "Cuadro Abstracto  ",
                                description: "Cuadro Abstracto Cielo con Nubes",
                                precio: 110000,
                                id: "c8"
                            },
                            {
                                img: "/img/trakihome/trakihome15.jpg",
                                name: "Archivador Aéreo",
                                description: "Archivador aéreo en madera modular",
                                precio: 130000,
                                id: "c9"
                            },
                            {
                                img: "/img/trakihome/trakihome16.jpg",
                                name: "Base Cama ",
                                description: "La Base Cama Versalles Doble de diseño moderno y elegante",
                                precio: 20000,
                                id: "c10"
                            },


                        ]}

                    />
                </Container>

            </Layout>

        </>
    )
}
