import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Header } from '../components/Header'
import { ContentCol } from '../components/ContentCol'
import { ImagesProduct } from '../components/ImagesProduct'
import { Footer } from '@/components/Footer'
import { CategoriProduct } from '@/components/CategoriProduct'
import { Home } from '@/SVG/home'
import { Woman } from '@/SVG/woman'
import { Niños } from '@/SVG/niños'
import { Man } from '@/SVG/man'
import { Layout } from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>Traki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        <CategoriProduct
          nameCategory='TRK Home'
          svgCategory={(<>
            <Home />
          </>)}
          listCategorias={[
            {
              img: "/img/trakihome1.1.jpg",
              text: "Lo nuevo en TRK Home",
              button: "Descubre Mas",
            },
            {
              img: "/img/trakihome2.jpg",
              text: "Decora tu hogar con TRK Home",
              button: "Descubre Mas",
            },
            {
              img: "/img/trakihome3.jpg",
              text: "Acercate a TRK Home",
              button: "Descubre Mas",
            },
          ]}

        />

        <CategoriProduct
          nameCategory='TRK Woman'
          svgCategory={(<>
            <Woman />
          </>)}
          listCategorias={[
            {
              img: "/img/trakiwoman1.jpg",
              text: "Lo nuevo en TRK woman",
              button: "Descubre Mas",

            },

            {
              img: "/img/trakiwoman2.jpg",
              text: "Inspirate en lo ultimo de la moda",
              button: "Descubre Mas",

            },
            {
              img: "/img/trakiwoman3.jpg",
              text: "Mira un poco mas TRK woman",
              button: "Descubre Mas",
            }
          ]}

        />

        <CategoriProduct
          nameCategory='TRK Kids'
          svgCategory={(<>
            < Niños />
          </>)}
          listCategorias={[
            {
              img: "/img/trakids1.jpg",
              text: "Encuentra lo mas cool en TRK Kids",
              button: "Descubre Mas",

            },

            {
              img: "/img/trakids2.jpg",
              text: "Paro los pequeños de la casa",
              button: "Descubre Mas",

            },
            {
              img: "/img/trakids3.jpg",
              text: "Mira un poco mas TRK Kids",
              button: "Descubre Mas",
            }
          ]}

        />
        <CategoriProduct
          nameCategory='TRK Man'
          svgCategory={(<>
            < Man />
          </>)}
          listCategorias={[
            {
              img: "/img/trakiMan1.jpg",
              text: "Encuentra la moda en  TRK Man",
              button: "Descubre Mas",

            },

            {
              img: "/img/trakiMan2.jpg",
              text: "Disponible en TRK Man",
              button: "Descubre Mas",

            },
            {
              img: "/img/trakiMan3.jpg",
              text: "Combina tus Looks",
              button: "Descubre Mas",
            }
          ]}

        />


      </Layout>



    </>

  )
}
