import Head from 'next/head'
import { Inter } from 'next/font/google'
import { CategoriProduct } from '@/components/CategoriProduct'
import { Home } from '@/SVG/home'
import { Woman } from '@/SVG/woman'
import { Niños } from '@/SVG/niños'
import { Man } from '@/SVG/man'
import { Layout } from '@/components/Layout'
import { ThemeContent } from '@/components/ThemeContent'
import { getUsers } from '../fetch/Users'
import { UserList } from '@/components/UserList'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  getUsers()
  return (
    <>
      <Head>
        <title>Traki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserList/>
      <Layout>
        <ThemeContent
          circleProduct={
            [
              {
                circleimg: "/img/trakiwoman/trakiwoman6.jpg",
                texto: "Damas",
              },
              {
                circleimg: "/img/trakihome/trakihome5.jpg",
                texto: "Hogar",
              },
              {
                circleimg: "/img/trakiman/TrakiMan8.jpg",
                texto: "Caballero",
              },
              {
                circleimg: "/img/trakiluminacion/trakiluminacion.jpg",
                texto: "Iluminacion",
              },
              {
                circleimg: "/img/trakielectrodomesticos/trakielectrodomesticos.jfif",
                texto: "Electrodomesticos",
              },

            ]

          }



        />
        <CategoriProduct
          nameCategory='TRK Home'
          svgCategory={(<>
            <Home />
          </>)}
          listCategorias={[
            {
              img: "/img/trakihome/trakihome1.1.jpg",
              text: "Lo nuevo en TRK Home",
              button: "Descubre Mas",
            },
            {
              img: "/img/trakihome/trakihome2.jpg",
              text: "Decora tu hogar con TRK Home",
              button: "Descubre Mas",
            },
            {
              img: "/img/trakihome/trakihome3.jpg",
              text: "Acercate a TRK Home",
              button: "Descubre Mas",
            },
          ]}

        />

        <CategoriProduct
          nameCategory='TRK Woman'
          svgCategory={(<>
            <Woman />
          </>)}
          listCategorias={[
            {
              img: "/img/trakiwoman/trakiwoman1.jpg",
              text: "Lo nuevo en TRK woman",
              button: "Descubre Mas",

            },

            {
              img: "/img/trakiwoman/trakiwoman2.jpg",
              text: "Inspirate en lo ultimo de la moda",
              button: "Descubre Mas",

            },
            {
              img: "/img/trakiwoman/trakiwoman3.jpg",
              text: "Mira un poco mas TRK woman",
              button: "Descubre Mas",
            }
          ]}

        />

        <CategoriProduct
          nameCategory='TRK Kids'
          svgCategory={(<>
            < Niños />
          </>)}
          listCategorias={[
            {
              img: "/img/trakids1.jpg",
              text: "Encuentra lo mas cool en TRK Kids",
              button: "Descubre Mas",

            },

            {
              img: "/img/trakids2.jpg",
              text: "Paro los pequeños de la casa",
              button: "Descubre Mas",

            },
            {
              img: "/img/trakids3.jpg",
              text: "Mira un poco mas TRK Kids",
              button: "Descubre Mas",
            }
          ]}

        />
        <CategoriProduct
          nameCategory='TRK Man'
          svgCategory={(<>
            < Man />
          </>)}
          listCategorias={[
            {
              img: "/img/trakiman/TrakiMan1.jpg",
              text: "Encuentra la moda en  TRK Man",
              button: "Descubre Mas",

            },

            {
              img: "/img/trakiman/trakiMan2.jpg",
              text: "Disponible en TRK Man",
              button: "Descubre Mas",

            },
            {
              img: "/img/trakiman/TrakiMan3.jpg",
              text: "Combina tus Looks",
              button: "Descubre Mas",
            }
          ]}

        />


      </Layout>



    </>

  )
}
