
import { Container } from '@/components/Container'
import { Layout } from '@/components/Layout'
import { ListProductViews } from '@/components/ListProductViews'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Mobiliario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Container>
                    <ListProductViews
                        productViews={[


                            {
                                img: "/img/trakihome/mobiliario1.jpg",
                                name: "Sofá Cama ",
                                description: "El Sofá cuenta con una structura de madera pino  naturalmente",
                                precio: 180000,
                                id: "m1"
                            },
                            {
                                img: "/img/trakihome/mobiliario2.jpg",
                                name: "Sala Modular",
                                description: "La Sala Modular Alcalá es de diseño sobrio. moderno y elegante.",
                                precio: 25000,
                                id: "m2"
                            },
                            {
                                img: "/img/trakihome/mobiliario3.jpg",
                                name: " Sala Baltimore ",
                                description: "Elaborada con una estructura de madera pino ",
                                precio: 100000,
                                id: "m3"
                            },
                            {
                                img: "/img/trakihome/mobiliario4.jpg",
                                name: "Armario Lisboa",
                                description: "Armario con dos cajones, diseño moderno, facil armado, amplios espacios para guardar y organizar",
                                precio: 100000,
                                id: "m4"
                            },
                            {
                                img: "/img/trakihome/mobiliario5.jpg",
                                name: "Puff Lisboa",
                                description: "Fabricado con tela poliester",
                                precio: 25000,
                                id: "m5"
                            },
                            {
                                img: "/img/trakihome/mobiliario6.jpg",
                                name: "Combo de estudio",
                                description: "  Escritorio  con amplio espacio de trabajo",
                                precio: 13000,
                                id: "m6"
                            },
                   
                            {
                                img: "/img/trakihome/trakihome15.jpg",
                                name: "Archivador Aéreo",
                                description: "Archivador aéreo en madera modular",
                                precio: 130000,
                                id: "m7"
                            },
                            {
                                img: "/img/trakihome/trakihome16.jpg",
                                name: "Base Cama ",
                                description: "La Base Cama Versalles Doble de diseño moderno y elegante",
                                precio: 20000,
                                id: "m8"
                            },

                            {
                                img: "/img/trakihome/trakihome7.jpg",
                                name: "Mueble para TV hasta 50” Andorra Bellota",
                                description: "Mueble para tv con, espacio para almacenar ",
                                precio: 180000,
                                id: "m9"
                            },
                            {
                                img: "/img/trakihome/trakihome8.jpg",
                                name: "Mesa de noche Hanaki",
                                description: "Mesa de noche Hanaki",
                                precio: 25000,
                                id: "m10"
                            },
                            {
                                img: "/img/trakihome/trakihome9.jpg",
                                name: " Comedor Marsella ",
                                description: "Mesa de Comedor Marsella 4 Puestos",
                                precio: 100000,
                                id: "m11"
                            },
                            {
                                img: "/img/trakihome/trakihome10.jpg",
                                name: "Gabinete de baño",
                                description: "Tiene espejo. Es de muy fácil armado,",
                                precio: 100000,
                                id: "m12"
                            },
                            {
                                img: "/img/trakihome/trakihome11.jpg",
                                name: "Silla Barra Dais negra ",
                                description: "Cuero Sintético",
                                precio: 25000,
                                id: "m13"
                            },
                           


                        ]}

                    />
                </Container>

            </Layout>

        </>
    )
}
